
spring:
  application:
    name: StorageService
  servlet:
    multipart:
      # Включаем поддержку multipart (в Spring Boot обычно true по умолчанию)
      enabled: true
      # Максимальный размер ОДНОГО файла
      max-file-size: 50MB
      # Максимальный размер ВСЕГО запроса (файл + текстовые поля + заголовки)
      max-request-size: 55MB
      # Порог, после которого файл пишется на диск, а не держится в памяти
      file-size-threshold: 2KB

minio:
  url: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: cloud-storage

#kafka:
#  bootstrap-servers: localhost:29092

#metadata:
#  service-url: http://localhost:8081    # ????? metadata-service (dev)

  management:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    endpoint:
      health:
        show-details: always
server:
  port: 8082

logging:
  level:
    org.springframework.web: DEBUG
    # Это покажет сырой HTTP поток, если нужно копнуть глубже
    org.apache.coyote.http11: DEBUG
