server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/metadata
    username: metadata
    password: metadata

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: metadata-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.denisbondd111.common.event
        spring.json.value.default.type: com.denisbondd111.common.event.FileUploadedEvent
